--Antes de tudo é necessário acessar o psql com um user conhecido, após login em alguma database é necessário executar os scripts abaixo

--Criando database
CREATE DATABASE savetimetest WITH ENCODING 'UTF8' LC_COLLATE='Portuguese_Brazil.1252' LC_CTYPE='Portuguese_Brazil.1252';

--Acessando database
\c savetimetest

--Criando tabelas

CREATE TABLE ST_USER (
ID SERIAL PRIMARY KEY,
LOGIN VARCHAR,
SENHA VARCHAR,
NOME VARCHAR
);

INSERT INTO ST_USER (LOGIN,SENHA,NOME) VALUES ('ADMIN','savepass','ADMINISTRADOR SISTEMA');
COMMIT;

CREATE TABLE ST_LEITURAS (
ID SERIAL PRIMARY KEY,
ID_USUARIO INTEGER,
NOME_LIVRO VARCHAR,
TOTAL_PAGINAS VARCHAR,
PAGINA_ATUAL VARCHAR,
DATA_ATUAL DATE,
TEMPO_GASTO VARCHAR,
CONCLUSAO DATE,
FOREIGN KEY (ID_USUARIO) REFERENCES ST_USER(ID)
);

CREATE TABLE ST_EXERCICIOS (
ID SERIAL PRIMARY KEY,
ID_USUARIO INTEGER,
EXERCICIO VARCHAR,
DATA_ATUAL DATE,
TEMPO_GASTO VARCHAR,
FOREIGN KEY (ID_USUARIO) REFERENCES ST_USER(ID)
);

CREATE TABLE ST_CURSOS (
ID SERIAL PRIMARY KEY,
ID_USUARIO INTEGER,
CURSO VARCHAR,
DATA_ATUAL DATE,
TEMPO_GASTO VARCHAR,
TOTAL_AULAS INTEGER,
AULA_ATUAL INTEGER,
CONCLUSAO DATE,
FOREIGN KEY (ID_USUARIO) REFERENCES ST_USER(ID)
);

CREATE TABLE ST_IDIOMAS (
ID SERIAL PRIMARY KEY,
ID_USUARIO INTEGER,
IDIOMA VARCHAR,
DATA_ATUAL DATE,
TEMPO_GASTO VARCHAR,
FOREIGN KEY (ID_USUARIO) REFERENCES ST_USER(ID)
);

CREATE TABLE ST_ESPIRITUAL (
ID SERIAL PRIMARY KEY,
ID_USUARIO INTEGER,
ATIVIDADE VARCHAR,
DATA_ATUAL DATE,
TEMPO_GASTO VARCHAR,
FOREIGN KEY (ID_USUARIO) REFERENCES ST_USER(ID)
);

CREATE TABLE ST_DIETAS (
ID SERIAL PRIMARY KEY,
ID_USUARIO INTEGER,
DATA_ATUAL DATE,
HORARIO VARCHAR,
REFEICAO VARCHAR,
QUANTIDADE VARCHAR,
ALIMENTO VARCHAR,
FOREIGN KEY (ID_USUARIO) REFERENCES ST_USER(ID)
);

--Criando usuário da aplicação
CREATE USER saveadmin WITH ENCRYPTED PASSWORD 'saveadmin2021';

--Dando Permissões para o usuário
GRANT ALL PRIVILEGES ON DATABASE savetimetest TO saveadmin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO saveadmin;

--Fim